//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsEmployee.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id_emp { get; set; }
        public string nom_emp { get; set; }
        public string prenom_emp { get; set; }
        public double Salaire_emp { get; set; }
        public System.DateTime date_recrute_emp { get; set; }
        public double tele_emp { get; set; }
        public int id_dep { get; set; }
    
        public virtual Departement Departement { get; set; }
    }
}
